name: Deploy Flutter Web Frontend

on:
  push:
    branches:
      - mainnew
    paths:
      - "lib/**"
      - "web/**"
      - "assets/**"
      - "pubspec.yaml"
      - "pubspec.lock"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Debug - List Build Files
        run: |
          echo "Checking if build/web exists..."
          ls -la build/web/

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 135.181.46.27 >> ~/.ssh/known_hosts

      - name: Deploy to Hetzner (Flutter Web)
        run: |
          # --verbose (v) lagaya hai taake logs mein file names dikhein
          rsync -avz --progress build/web/ root@135.181.46.27:/var/www/nexatrace/frontend/